# Generated by Django 4.0.3 on 2022-04-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_useractivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivation',
            old_name='otp',
            new_name='user_otp',
        ),
    ]
