# Generated by Django 4.0.3 on 2022-04-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_otp_useractivation_user_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Otp',
            new_name='ActivateOtp',
        ),
        migrations.RenameModel(
            old_name='UserActivation',
            new_name='PassOtp',
        ),
    ]
