# Generated by Django 4.0.3 on 2022-04-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_otp_activateotp_rename_useractivation_passotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
