# Generated by Django 4.0.3 on 2022-04-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_passotp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivateOtp',
        ),
    ]
